---
- name : playbook_lab2.yml
  hosts: control_node 
  gather_facts: yes
  tasks:
   - debug:
       var: ansible_local 
   - debug:
       var: ansible_local.{{ansible_hostname}}.our_class.class_name
   - debug:
       var: ansible_local.{{ansible_hostname}}.our_class.instructor
