# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export PATH=/bin:/usr/bin:/sbin:/usr/sbin:.
export EDITOR=vim
#export ANSIBLE_INVENTORY=/home/ansadm/hosts_2

PS1='ansadm-control_node> '

alias cp='cp -i'
alias rm='rm -i'
alias mv='mv -i'
alias pb=ansible-playbook
