---
- name : playbook16.yml
  hosts: control_node 
  gather_facts: no
  become: true

  tasks:
  - name: create user account
    user:
      name: "{{ item }}"
      home: "/home/{{ item }}"
      shell: /bin/bash
    with_items:
      - user62 
      - user63 
