---
- name: playbook9.yml
  hosts: control_node 
  vars:
   var1: "value1"
  vars_files:
  - variables.yml

  tasks:
    - shell: uname
      register: var3

    - debug:
        var: var1
    - debug:
        msg: "value of var1 {{var1}}"
    - debug:
        var: var2
    - debug:
        msg: "value of var2 {{var2}}"
    - debug:
        var: var3.stdout
    - debug:
        msg: "{{var3.stdout}}"
