---
- name : playbook33.yml
  hosts: control_node
  become: true
  tasks:
  - name: install httpd 
    yum:
      name: httpd
      state: latest 
    when: 
      - ansible_os_family == "RedHat"
      - ansible_distribution == "OracleLinux"
