---
- name : playbook14.yml
  hosts: control_node 
  become: true
  tasks:
  - name: install httpd 
    yum:
      name: httpd
      state: latest 

  - name: change httpd.conf file
    lineinfile:
     path: /etc/httpd/conf/httpd.conf
     regexp: '^#ServerName'
     line: "ServerName {{ansible_nodename}}:80"
     backrefs: yes
