---
- name : playbook36.yml
  hosts: control_node 
  gather_facts: no
  become: true

  tasks:
  - name: create user accounts
    user:
      name: "{{ item[0] }}"
      home: "/home/{{ item[1] }}"
      shell: /bin/bash
    with_nested:
      - [ 'user62','user63' ]
      - [ 'user62','user63' ]
