# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export PATH=/bin:/usr/bin:/sbin:/usr/sbin:.
export EDITOR=vim

PS1='$LOGNAME> '

alias cp='cp -i'
alias rm='rm -i'
alias mv='mv -i'
alias pb=ansible-playbook
