---
- name : playbook30.yml
  hosts: managed_node,control_node 
  gather_facts: no 
  strategy: linear
  tasks:
  - name: first sleep
    shell: sleep "{{ seconds }}"

  - name: second sleep
    shell: sleep "{{ seconds }}"
