---
- name : playbook20.yml
  hosts: control_node 
  gather_facts: False
  become: true
  tasks:
  - name: install httpd 
    yum:
      name: httpd
      state: latest 
    notify: 
    - broadcast blast
    - logger message 
  
  handlers:
  - name: broadcast blast 
    shell: wall "httpd package installed"

  - name: logger message 
    shell: logger -p daemon.notice "httpd installed" 
