---
- name : playbook3.yml
  hosts: control_node 
  gather_facts: yes
  tasks:
   - shell: echo "on Oracle Linux"
     register: output 

   - debug:
       var: output.stdout_lines
   - debug:
       msg: "{{output.stdout_lines}}"
     when:  ansible_distribution  == "OracleLinux"
