---
- name : playbook15.yml
  hosts: control_node
  become: true
  tasks:
  - name: install httpd 
    yum:
      name: httpd
      state: latest 
    when: ansible_os_family == "RedHat"

  - name: change httpd.conf file
    lineinfile:
     path: /etc/httpd/conf/httpd.conf
     regexp: '^#ServerName'
     line: "ServerName {{ansible_nodename}}:80"
    when: ansible_os_family == "RedHat"

  - debug: "msg='running on:'{{ansible_os_family}}"
